# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_motion_group
  joint_model_group_pose: "Test "
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - j1_to_base
    - j2_to_j1
    - j3_to_j2
    - j4_to_j3
    - j5_to_j4
    - j6_to_j5
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_motion_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j1_to_base
      - j2_to_j1
      - j3_to_j2
      - j4_to_j3
      - j5_to_j4
      - j6_to_j5

arm_motion_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
      - j1_to_base
      - j2_to_j1
      - j3_to_j2
      - j4_to_j3
      - j5_to_j4
      - j6_to_j5
  gains:
    j1_to_base: { p: 500, d: 50, i: 0.0, i_clamp: 1 }
    j2_to_j1: { p: 400, d: 100, i: 0.02, i_clamp: 1 }
    j3_to_j2: { p: 300, d: 50, i: 0.01, i_clamp: 1 }
    j4_to_j3: { p: 200, d: 70, i: 0.01, i_clamp: 1 }
    j5_to_j4: { p: 100, d: 70, i: 0.01, i_clamp: 1 }
    j6_to_j5: { p: 50, d: 50, i: 0.01, i_clamp: 1 }
  constraints:
    goal_time: 0.9

  state_publish_rate: 25
